### ISSUE TITLE
Conditional `And` effects

### ISSUE THREAD

**Issue by haz** [AI-Planning/pddl#118]
Shouldn't [[this line](https://github.com/AI-Planning/pddl/blob/main/pddl/parser/domain.py#L290)] use `AndEffect` instead of `And`?

**Comment by francescofuggitti** [comment]
This was actually fixed the other way around in [https://github.com/AI-Planning/pddl/pull/35/commits/a713b010ca2d351d9bec5f760d97209439958d24](https://github.com/AI-Planning/pddl/pull/35/commits/a713b010ca2d351d9bec5f760d97209439958d24) long time back...I don't remember exactly why we introduced the `AndEffect` class at all --perhaps to fix a stringify problem. Anyway, at first sight, from the `domain.lark` grammar, it seems that the `AndEffect` is just a wrapper for the outest "And" in an effect, so in the highlighted line the correct use should be the `And` class?

**Comment by haz** [comment]
Well there are two cases here: (1) we have a separate use of `(and ...)` in conditions -vs- effects, or (2) we don't.

If it's (1), then that line should be `AndEffect`, since it's the consequent of the conditional. If it's (2), then we need to nuke the `AndEffect` entirely. You can see how it starts to be required here: https://github.com/AI-Planning/pddl/blob/8e3be082c0c2142288ffb14a9766f66bd9b1febf/pddl/logic/effects.py#L170

I ran into issues trying to both parse PDDL, and then write new PDDL, with condeffs in play. If curious, it's this: https://github.com/AI-Planning/fond-utils/blob/main/normalizer.py

So I'm happy with (2) -- removing `AndEffect` everywhere -- and these would be the touch points:
- All mentions: https://github.com/search?q=repo%3AAI-Planning%2Fpddl%20AndEffect&type=code
- Difference between em:
  - https://github.com/AI-Planning/pddl/blob/8e3be082c0c2142288ffb14a9766f66bd9b1febf/pddl/logic/effects.py#L28
  - https://github.com/AI-Planning/pddl/blob/main/pddl/logic/base.py#L135

**Comment by haz** [comment]
CC @marcofavorito : Bringing you into the conversation here as well, since this issue is next on my list.

**Comment by francescofuggitti** [comment]
Thanks for the recap. In general, I would avoid option (1) as it introduces unnecessary complexity and reduces code readability. In the long run, I'd prefer option (2), and it seems there are only a few touch points so it may be easy to apply.

Currently, for reasons I can't recall and couldn't retrieve today, we are already on track with option (1). If you need to proceed quickly, it might be best to apply the fix (i.e., changing from And to AndEffect in the condeffs). We can always open a new issue and add this to the backlog for further discussion/implementation. Furthermore, on this, some time ago, I discussed with @marcofavorito about making the `Effect` into a more general `Formula`, which may be relevant in the case of a new general code refactoring.

**Comment by haz** [comment]
Nah, I'm fine running with (2). Just wanted to make sure I wasn't missing some broader implication:
1. `@functools.total_ordering` is on `AndEffect`. Do we forgo needing that or port over to `And`?
2. Similarly, `AndEffect` defines `__lt__` over [[here](https://github.com/AI-Planning/pddl/blob/8e3be082c0c2142288ffb14a9766f66bd9b1febf/pddl/logic/effects.py#L56)]. Do we need that on a unified `And`?
3. The `And` class has a few special things [[here](https://github.com/AI-Planning/pddl/blob/main/pddl/logic/base.py#L138-L139)]. Any issue with those being a part of `AndEffect`?

With answers to the above, I can move ahead with option (2): fold the `AndEffect` into `And`.

**Comment by marcofavorito** [comment]
Hi guys, I am happy with (2) as well. 

However, this choice has some implications on the class hierarchy of `Formula` and `Effect`, as Francesco said. 

If `Effect` and `Formula` are **not** fundamentally different, then it is fine to merge them. 

Otherwise, it might happen that at some point, we need to distinguish whether a syntax tree is a "pure formula" or an effect, and so implement functions like `is_effect(f)`, etc., it is a design choice to make.

One critical expression, for example, is `When`. Is it true that, whenever a `Formula` object is expected in the library, `When` is a valid Formula (e.g. in action preconditions, see https://github.com/AI-Planning/pddl/blob/main/pddl/action.py#L30)? 

In fact, a similar issue might hold for the `OneOf` expression, which currently is considered a `BinaryOp` (hence, a `Formula`) but I don't know whether it is "legal" for PDDL parsers to be used as a precondition (semantically speaking, it can just be replaced by an `Or` when appears in a precondition).

**Comment by haz** [comment]
Ah, right. I don't want to conflate `or` and `oneof`. Former should never be an effect (but may be a condition of a condeff), and latter should never be a condition. I guess this is where the distinction comes into play...are you parsing (or building) for a formula (evaluations to true) or effect (changes the world). For most of the syntax, the keywords implicitly capture this (`or` is always condition and `oneof` is always effect).

What about an option (3)? We go with (1), but we allow the `And` to be cast as an `AndEffect` when it's used in that context? I kind of like the `p & q` shorthand syntax for both `And` and `AndEffect`, and it would be a shame to give up on the latter (as #119 does).

**Comment by haz** [comment]
Now I'm talking myself into a corner...by the same logic of having `And` / `AndEffect` disjoint, we should adopt two notions for `Predicate`. One of which is a formula ( https://github.com/AI-Planning/pddl/blob/main/pddl/logic/predicates.py#L46 ) that evaluates to true/false in a state, and the other of which is an effect that's added or removed from a state.

So I'm back to leaning towards (2) -- just unify those effect-based things that overlap with formulae, and be careful about how/when they're used.

**Comment by marcofavorito** [comment]
Good point, yes let's follow solution (2). I don't mind to implement it if no one else can/want to.

Thank you guys for the useful discussion and for sharing your insights.

**Comment by haz** [comment]
I took a crack at it. #119 is ready for review, and please note the comments I left on the diff. Resolve if they seem fine. Rest seems pretty benign.

**Comment by haz** [comment]
Resolved with #119
