### ISSUE TITLE
MIT License?

### ISSUE THREAD

**Issue by haz** [AI-Planning/pddl#33]
**Is your feature request related to a problem? Please describe.**
Would love to see the license change.

**Describe the solution you'd like**
LGPL -> MIT

**Describe alternatives you've considered**
BSD, Apache, ...

**Additional context**
Would love to see it happen!

**Comment by francescofuggitti** [comment]
Will come soon! :rocket:

**Comment by haz** [comment]
Something holding it up?

**Comment by francescofuggitti** [comment]
No, just too many upcoming deadlines...

**Comment by haz** [comment]
There something that would take time for it? Happy to jump on some of the other issues, but a license change seems to be something that should come from you guys :P (and before I run with anything else).

**Comment by francescofuggitti** [comment]
Thanks @marcofavorito!

**Comment by francescofuggitti** [comment]
The badge has been updated too. It just needs to be merged to master and it will be updated. To make the process easier, we can work on features directly opening branches from the master and then merging into it. Once we are satisfied with a certain number of features, we can tag it and release a new updated version. Does that sound good?

**Comment by haz** [comment]
Yep, for sure! There are many models of development for release maintenance -- was just curious which one you liked to follow.

Any smart tricks to auto-tag the version? I inevitably always forget to bump the version number when I create a release, which has pypi complaining.
