### ISSUE TITLE
Support for Python 3.9, 3.10 and 3.11

### ISSUE THREAD

**Issue by marcofavorito** [AI-Planning/pddl#45]
**Is your feature request related to a problem? Please describe.**
The package only supports 3.6, 3.7 and 3.8. Support for 3.6 is going to be removed in this PR #44 (if accepted).

**Describe the solution you'd like**
The package should support Python 3.9, 3.10 and 3.11; some of these are default Python versions of LTS versions of Linux distribution (e.g. Ubuntu), or other operating systems.

**Describe alternatives you've considered**
n/a

**Additional context**
Should not add development costs. We must add them in the GitHub Actions workflow configurations to see whether there are issues in tests/linting.

**Comment by bpshaver** [comment]
I took a crack at this here: https://github.com/AI-Planning/pddl/pull/58
