### ISSUE TITLE
Pypi integration

### ISSUE THREAD

**Issue by haz** [AI-Planning/pddl#51]
**Is your feature request related to a problem? Please describe.**
Upon GitHub release, a new version should be pushed to pypi.

**Describe the solution you'd like**
GitHub actions. Usual template.

**Describe alternatives you've considered**
Manually doing this. It's a pain.

**Comment by haz** [comment]
@marcofavorito @francescofuggitti : This is in place, save one final element.

1. Head to pypi.org
2. Click on "Manage" for the `pddl` project
3. Click on "Settings"
4. Click "Create a token for pddl"
5. Copy what's there (once you close that site, you can't get it back)
6. Head over [[here](https://github.com/AI-Planning/pddl/settings/secrets/actions)]
7. Add the token copied in step 5 to the "Repository secrets" as `PYPI_API_TOKEN`

Once that's done, [this](https://github.com/AI-Planning/pddl/blob/main/.github/workflows/python-publish.yml) workflow will auto-publish new versions to pypi whenever a new release is created. Just need to be sure to update [this file](https://github.com/AI-Planning/pddl/blob/main/pddl/__version__.py) before making the release.

**Comment by francescofuggitti** [comment]
Thank you Christian!
