### ISSUE TITLE
Unable to pickle or deepcopy Domains, Actions, Problems

### ISSUE THREAD

**Issue by James-Oswald** [AI-Planning/pddl#79]
### Subject of the issue
The cache hashing mechanism appears to break my ability to deepcopy or pickle any of the core objects. 

### Your environment
- OS: Red Hat Enterprise Linux release 8.7
- Python version: 3.9.13
- Package Version 3.1

### Steps to reproduce
Minimally reproducible example for domains, same issue with actions and problems
```py
import copy
import pickle
import traceback

from pddl.parser.domain import DomainParser

domain_str = """
    (define (domain test)
        (:requirements :typing)
        (:types t1)
        (:constants c1 - t1)
        (:predicates  (p1 ?v1 - t1))
        (:action a1
        :parameters (?v - t1)
        :effect (c1))
)"""

domain = DomainParser()(domain_str)

#Deep copy domains
try:
    copy.deepcopy(domain)
except Exception:
    print(traceback.format_exc())

#Pickle domains
try:
    pickle.dumps(domain)
except Exception:
    print(traceback.format_exc())
```

### Expected behaviour
I should get a deepcopied/pickled domain/action/problem without any errors occurring.  

### Actual behaviour
All fails with KeyError: '__hash' in the `d.pop("__hash")` on `cache_hash.py` line 56.

**Comment by marcofavorito** [comment]
Thank you @James-Oswald for the issue. This is indeed an unintended behaviour.
