### ISSUE TITLE
:typing is not included in the :adl requirement

### ISSUE THREAD

**Issue by iwob** [AI-Planning/pddl#87]
### Subject of the issue
:typing is not included in the :adl requirement when it should according to the [BNF definition](http://www.plg.inf.uc3m.es/ipc2011-deterministic/attachments/Resources/kovacs-pddl-3.1-2011.pdf).

### Your environment
- OS: Ubuntu 22.04
- Python version: 3.10.12
- Package Version: downloaded from github, commit f54e1878109fed88ca56f3a18f3ecc7dd9fbe9eb of the main branch

### Steps to reproduce
Run the parser for the attached [tictactoe.txt](https://github.com/AI-Planning/pddl/files/12389383/tictactoe.txt) file.
```
from pddl import parse_domain, parse_problem
domain = parse_domain('tictactoe.txt')
```

### Expected behaviour
File parses correctly.

### Actual behaviour
```
pddl.exceptions.PDDLValidationError: typing requirement is not specified, but the following types were used: frozenset({'field'})
```

**Comment by francescofuggitti** [comment]
Thanks for spotting this, @iwob! Although with some delay, I've just solved the issue. Everything is in PR #90, which I think will be merged very soon.
